### PR TITLE
Fix yarn.lock

### PR DESCRIPTION
**Pull request by Alxandr**

### CODE REVIEW

**Comment by Alxandr** [comment]
Hmm. This came out wrong. Will re-create after lunch.

**Comment by andreypopp** [comment]
I merged your another PR already and fixed yarn.lock. Thanks!

**Comment by Alxandr** [comment]
The default npmrc on my machine is for work, and it's what I use 95% of the time, so it's way too easy to forget to switch back when needed. Apologies for not noticing.

**Comment by andreypopp** [comment]
np

**Pull request closed without merging**
