### PR TITLE
Remove lodash

### PR DESCRIPTION
**Pull request by soenkehahn**
Solves #12.

cc: @sleexyz

### CODE REVIEW

**Comment by andreypopp** [comment]
Thanks!

**Comment by andreypopp** [comment]
Released in 1.1.0.

**Comment by soenkehahn** [comment]
Awesome. Haven't had the chance to try it out, but thanks a lot for the timely release!

**Comment by soenkehahn** [comment]
Now I finally tried it out in a project, works like a charm. Awesome library!

**Pull request merged**
